// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdvancedConfig = { id: number, name: string | null, decoder: DecoderConfig, encoder: EncoderConfig, filter: FilterConfig, ingest: IngestConfig, };

export type DecoderConfig = { input_param: string, output_param: string, };

export type EncoderConfig = { input_param: string, };

export type FilterConfig = { deinterlace: string, pad_video: string, fps: string, scale: string, set_dar: string, fade_in: string, fade_out: string, logo: string, overlay_logo_scale: string, overlay_logo_fade_in: string, overlay_logo_fade_out: string, overlay_logo: string, tpad: string, drawtext_from_file: string, drawtext_from_zmq: string, aevalsrc: string, afade_in: string, afade_out: string, apad: string, volume: string, split: string, };

export type IngestConfig = { input_param: string, };
