// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type General = { stop_threshold: number, };

export type Ingest = { enable: boolean, ingest_url: string, };

export type Logging = { ffmpeg_level: string, ingest_level: string, detect_silence: boolean, ignore_lines: Array<string>, };

export type Mail = { show: boolean, subject: string, recipient: string, mail_level: string, interval: bigint, };

export type Output = { id: number, mode: OutputMode, stream_url: string, hls_playlist_name: string, hls_segment_duration: number, hls_list_size: number, width: number, height: number, fps: number, video_preset: string, rate_control: string, video_quality: number, video_maxrate: number, audio_bitrate: number,
/**
 * Adaptive HLS renditions, one per entry, each formatted as
 * `NAME:WIDTHxHEIGHT:VIDEO_BITRATE[:AUDIO_BITRATE]` (e.g.
 * `high:1920x1080:5000k:192k`). Only relevant when `mode == HLS`;
 * entries are added to the base rendition configured directly on this
 * output.
 */
hls_variants: Array<string>, };

export type OutputMode = "desktop" | "hls" | "stream";

export type Playlist = { day_start: string, length: string, infinit: boolean, };

/**
 * Channel Config
 *
 * This we init ones, when ffplayout is starting and use them globally in the hole program.
 */
export type PlayoutConfig = { general: General, mail: Mail, logging: Logging, processing: Processing, ingest: Ingest, playlist: Playlist, storage: Storage, text: Text, task: Task, output: Output, };

export type ProcessMode = "folder" | "playlist";

export type Processing = { mode: ProcessMode, add_logo: boolean, logo: string, logo_scale: string, logo_opacity: number, logo_position: string, volume: number, vtt_enable: boolean, vtt_dummy: string | null, vtt_name: string, vtt_language: string, vtt_default: boolean, };

export type Storage = { filler: string, extensions: Array<string>, shuffle: boolean, shared_storage: boolean, };

export type Task = { enable: boolean, path: string, };

export type Text = { preset_id: number | null, };
