# Generated by Django 3.0.5 on 2020-04-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_url', models.CharField(max_length=255)),
                ('playout_config', models.CharField(default='/etc/ffplayout/ffplayout.yml', max_length=255)),
                ('net_interface', models.CharField(choices=[('lo', 'lo'), ('br0', 'br0'), ('virbr0', 'virbr0'), ('eno1', 'eno1'), ('virbr0-nic', 'virbr0-nic')], default=None, max_length=20)),
                ('media_disk', models.CharField(default='/', help_text='should be a mount point, for statistics', max_length=255)),
                ('extra_extensions', models.CharField(blank=True, default='', help_text='file extensions, that are only visible in GUI', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'guisettings',
            },
        ),
    ]
