# Generated by Django 3.0.5 on 2020-04-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerUrl', models.CharField(max_length=255)),
                ('playoutConfig', models.CharField(max_length=255)),
                ('netInterface', models.CharField(max_length=20)),
                ('mediaDisk', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'guisettings',
            },
        ),
    ]
