# Generated by Django 3.0.5 on 2020-04-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guisettings',
            old_name='mediaDisk',
            new_name='media_disk',
        ),
        migrations.RenameField(
            model_name='guisettings',
            old_name='netInterface',
            new_name='net_interface',
        ),
        migrations.RenameField(
            model_name='guisettings',
            old_name='playerUrl',
            new_name='player_url',
        ),
        migrations.RenameField(
            model_name='guisettings',
            old_name='playoutConfig',
            new_name='playout_config',
        ),
    ]
